name: Test workflow with error

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Run tests
      run: |
        echo "Running tests..."
        exit 1