name: Test workflow with error

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Run tests
      run: |
        echo "Running tests..."
        exit 1